# preguntas.py
# Base de 50 preguntas como lista de diccionarios.
# Cada pregunta: dict con opciones en TUPLA (inmutable a proposito).
# categorias: jugadores | escudos | goles | datos
# dificultad: facil | medio | dificil
# Mundial Trivia Challenge - UTP 2026

LISTA_TRIVIA = [
    # ============ JUGADORES (identificar por foto) - 20 ============
    {
        "id": 1,
        "categoria": "jugadores",
        "dificultad": "facil",
        "pregunta": "¿Quién es este jugador argentino, campeón del Mundial 2022?",
        "imagen": "assets/jugadores/messi.png",
        "opciones": ("Ángel Di María", "Lionel Messi", "Julián Álvarez", "Paulo Dybala"),
        "correcta": 1,
    },
    {
        "id": 2,
        "categoria": "jugadores",
        "dificultad": "facil",
        "pregunta": "¿Quién es este delantero francés, estrella del PSG y Real Madrid?",
        "imagen": "assets/jugadores/mbappe.png",
        "opciones": ("Antoine Griezmann", "Ousmane Dembélé", "Kylian Mbappé", "Olivier Giroud"),
        "correcta": 2,
    },
    {
        "id": 3,
        "categoria": "jugadores",
        "dificultad": "facil",
        "pregunta": "¿Quién es este astro portugués, máximo goleador de selecciones?",
        "imagen": "assets/jugadores/cristiano.png",
        "opciones": ("Cristiano Ronaldo", "Bruno Fernandes", "João Félix", "Bernardo Silva"),
        "correcta": 0,
    },
    {
        "id": 4,
        "categoria": "jugadores",
        "dificultad": "facil",
        "pregunta": "¿Quién es este atacante brasileño, ex jugador del Barcelona y PSG?",
        "imagen": "assets/jugadores/neymar.png",
        "opciones": ("Richarlison", "Vinícius Jr.", "Neymar Jr.", "Rodrygo"),
        "correcta": 2,
    },
    {
        "id": 5,
        "categoria": "jugadores",
        "dificultad": "facil",
        "pregunta": "¿Quién es este extremo brasileño del Real Madrid?",
        "imagen": "assets/jugadores/vinicius.png",
        "opciones": ("Neymar Jr.", "Vinícius Jr.", "Raphinha", "Endrick"),
        "correcta": 1,
    },
    {
        "id": 6,
        "categoria": "jugadores",
        "dificultad": "facil",
        "pregunta": "¿Quién es este goleador noruego del Manchester City?",
        "imagen": "assets/jugadores/haaland.png",
        "opciones": ("Erling Haaland", "Martin Ødegaard", "Alexander Sørloth", "Joshua King"),
        "correcta": 0,
    },
    {
        "id": 7,
        "categoria": "jugadores",
        "dificultad": "facil",
        "pregunta": "¿Quién es este arquero argentino, ganador del Guante de Oro 2022?",
        "imagen": "assets/jugadores/dibu.png",
        "opciones": ("Franco Armani", "Gerónimo Rulli", "Emiliano 'Dibu' Martínez", "Juan Musso"),
        "correcta": 2,
    },
    {
        "id": 8,
        "categoria": "jugadores",
        "dificultad": "facil",
        "pregunta": "¿Quién es este mediocampista español del Barcelona, joya de La Masía?",
        "imagen": "assets/jugadores/pedri.png",
        "opciones": ("Gavi", "Pedri", "Fermín López", "Dani Olmo"),
        "correcta": 1,
    },
    {
        "id": 9,
        "categoria": "jugadores",
        "dificultad": "facil",
        "pregunta": "¿Quién es esta joven estrella española del Barcelona, dorsal 19?",
        "imagen": "assets/jugadores/yamal.png",
        "opciones": ("Nico Williams", "Ferran Torres", "Lamine Yamal", "Ansu Fati"),
        "correcta": 2,
    },
    {
        "id": 10,
        "categoria": "jugadores",
        "dificultad": "facil",
        "pregunta": "¿Quién es este delantero inglés, capitán de Inglaterra?",
        "imagen": "assets/jugadores/kane.png",
        "opciones": ("Marcus Rashford", "Harry Kane", "Jude Bellingham", "Phil Foden"),
        "correcta": 1,
    },
    {
        "id": 11,
        "categoria": "jugadores",
        "dificultad": "medio",
        "pregunta": "¿Quién es este mediocampista croata, Balón de Oro 2018?",
        "imagen": "assets/jugadores/modric.png",
        "opciones": ("Ivan Rakitić", "Mateo Kovačić", "Luka Modrić", "Marcelo Brozović"),
        "correcta": 2,
    },
    {
        "id": 12,
        "categoria": "jugadores",
        "dificultad": "medio",
        "pregunta": "¿Quién es este mediocampista inglés del Real Madrid?",
        "imagen": "assets/jugadores/bellingham.png",
        "opciones": ("Declan Rice", "Jude Bellingham", "Mason Mount", "Cole Palmer"),
        "correcta": 1,
    },
    {
        "id": 13,
        "categoria": "jugadores",
        "dificultad": "medio",
        "pregunta": "¿Quién es este defensor neerlandés, capitán del Liverpool?",
        "imagen": "assets/jugadores/vandijk.png",
        "opciones": ("Matthijs de Ligt", "Virgil van Dijk", "Nathan Aké", "Stefan de Vrij"),
        "correcta": 1,
    },
    {
        "id": 14,
        "categoria": "jugadores",
        "dificultad": "medio",
        "pregunta": "¿Quién es este mediocampista uruguayo del Real Madrid?",
        "imagen": "assets/jugadores/valverde.png",
        "opciones": ("Rodrigo Bentancur", "Nicolás de la Cruz", "Federico Valverde", "Manuel Ugarte"),
        "correcta": 2,
    },
    {
        "id": 15,
        "categoria": "jugadores",
        "dificultad": "medio",
        "pregunta": "¿Quién es este delantero peruano, máximo goleador histórico de Perú?",
        "imagen": "assets/jugadores/guerrero.png",
        "opciones": ("Jefferson Farfán", "Paolo Guerrero", "Gianluca Lapadula", "Edison Flores"),
        "correcta": 1,
    },
    {
        "id": 16,
        "categoria": "jugadores",
        "dificultad": "medio",
        "pregunta": "¿Quién es este '10' peruano, ídolo histórico que jugó el Mundial 2018?",
        "imagen": "assets/jugadores/cueva.png",
        "opciones": ("Christian Cueva", "André Carrillo", "Renato Tapia", "Yoshimar Yotún"),
        "correcta": 0,
    },
    {
        "id": 17,
        "categoria": "jugadores",
        "dificultad": "dificil",
        "pregunta": "¿Quién es esta leyenda brasileña, único jugador con 3 Mundiales ganados?",
        "imagen": "assets/jugadores/pele.png",
        "opciones": ("Garrincha", "Pelé", "Zico", "Romário"),
        "correcta": 1,
    },
    {
        "id": 18,
        "categoria": "jugadores",
        "dificultad": "dificil",
        "pregunta": "¿Quién es esta leyenda argentina, campeón del Mundial 1986?",
        "imagen": "assets/jugadores/maradona.png",
        "opciones": ("Mario Kempes", "Diego Maradona", "Daniel Passarella", "Jorge Valdano"),
        "correcta": 1,
    },
    {
        "id": 19,
        "categoria": "jugadores",
        "dificultad": "dificil",
        "pregunta": "¿Quién es este francés, campeón del mundo 1998 y leyenda del Real Madrid?",
        "imagen": "assets/jugadores/zidane.png",
        "opciones": ("Thierry Henry", "Zinedine Zidane", "Patrick Vieira", "Didier Deschamps"),
        "correcta": 1,
    },
    {
        "id": 20,
        "categoria": "jugadores",
        "dificultad": "dificil",
        "pregunta": "¿Quién es este brasileño apodado 'El Fenómeno', campeón en 1994 y 2002?",
        "imagen": "assets/jugadores/ronaldo.png",
        "opciones": ("Ronaldinho", "Rivaldo", "Ronaldo Nazário", "Adriano"),
        "correcta": 2,
    },

    # ============ ESCUDOS (identificar seleccion) - 10 ============
    {
        "id": 21,
        "categoria": "escudos",
        "dificultad": "facil",
        "pregunta": "¿A qué selección pertenece este escudo (la 'Canarinha', 5 estrellas)?",
        "imagen": "assets/escudos/brasil.png",
        "opciones": ("Argentina", "Brasil", "Portugal", "Colombia"),
        "correcta": 1,
    },
    {
        "id": 22,
        "categoria": "escudos",
        "dificultad": "facil",
        "pregunta": "¿A qué selección pertenece este escudo (la 'Albiceleste', 3 estrellas)?",
        "imagen": "assets/escudos/argentina.png",
        "opciones": ("Uruguay", "Chile", "Argentina", "Paraguay"),
        "correcta": 2,
    },
    {
        "id": 23,
        "categoria": "escudos",
        "dificultad": "facil",
        "pregunta": "¿A qué selección pertenece este escudo (el gallo galo)?",
        "imagen": "assets/escudos/francia.png",
        "opciones": ("Bélgica", "Francia", "Suiza", "Países Bajos"),
        "correcta": 1,
    },
    {
        "id": 24,
        "categoria": "escudos",
        "dificultad": "facil",
        "pregunta": "¿A qué selección pertenece este escudo (la 'Blanquirroja')?",
        "imagen": "assets/escudos/peru.png",
        "opciones": ("Perú", "Chile", "Polonia", "Austria"),
        "correcta": 0,
    },
    {
        "id": 25,
        "categoria": "escudos",
        "dificultad": "medio",
        "pregunta": "¿A qué selección pertenece este escudo (el águila y 4 estrellas)?",
        "imagen": "assets/escudos/alemania.png",
        "opciones": ("Austria", "Polonia", "Alemania", "Serbia"),
        "correcta": 2,
    },
    {
        "id": 26,
        "categoria": "escudos",
        "dificultad": "medio",
        "pregunta": "¿A qué selección pertenece este escudo a cuadros rojos y blancos?",
        "imagen": "assets/escudos/croacia.png",
        "opciones": ("Eslovaquia", "Croacia", "Serbia", "Eslovenia"),
        "correcta": 1,
    },
    {
        "id": 27,
        "categoria": "escudos",
        "dificultad": "medio",
        "pregunta": "¿A qué selección pertenece este escudo (los 'Tres Leones')?",
        "imagen": "assets/escudos/inglaterra.png",
        "opciones": ("Escocia", "Gales", "Inglaterra", "Irlanda"),
        "correcta": 2,
    },
    {
        "id": 28,
        "categoria": "escudos",
        "dificultad": "medio",
        "pregunta": "¿A qué selección pertenece este escudo (la 'Celeste', 4 estrellas)?",
        "imagen": "assets/escudos/uruguay.png",
        "opciones": ("Argentina", "Honduras", "El Salvador", "Uruguay"),
        "correcta": 3,
    },
    {
        "id": 29,
        "categoria": "escudos",
        "dificultad": "dificil",
        "pregunta": "¿A qué selección pertenece este escudo (la 'Azzurra', 4 estrellas)?",
        "imagen": "assets/escudos/italia.png",
        "opciones": ("Francia", "Italia", "San Marino", "Malta"),
        "correcta": 1,
    },
    {
        "id": 30,
        "categoria": "escudos",
        "dificultad": "dificil",
        "pregunta": "¿A qué selección pertenece este escudo africano (las 'Estrellas Negras')?",
        "imagen": "assets/escudos/ghana.png",
        "opciones": ("Nigeria", "Senegal", "Ghana", "Camerún"),
        "correcta": 2,
    },

    # ============ GOLES HISTORICOS - 8 ============
    {
        "id": 31,
        "categoria": "goles",
        "dificultad": "medio",
        "pregunta": "¿De quién es este gol conocido como 'La Mano de Dios' (México 1986)?",
        "imagen": "assets/goles/mano_de_dios.png",
        "opciones": ("Mario Kempes", "Diego Maradona", "Jorge Burruchaga", "Claudio Caniggia"),
        "correcta": 1,
    },
    {
        "id": 32,
        "categoria": "goles",
        "dificultad": "medio",
        "pregunta": "¿Quién marcó este gol que le dio a España su único Mundial (2010)?",
        "imagen": "assets/goles/iniesta_2010.png",
        "opciones": ("David Villa", "Fernando Torres", "Andrés Iniesta", "Xavi Hernández"),
        "correcta": 2,
    },
    {
        "id": 33,
        "categoria": "goles",
        "dificultad": "medio",
        "pregunta": "¿Quién marcó este gol de cabeza en la final de Alemania 2014?",
        "imagen": "assets/goles/gotze_2014.png",
        "opciones": ("Thomas Müller", "Mario Götze", "Miroslav Klose", "André Schürrle"),
        "correcta": 1,
    },
    {
        "id": 34,
        "categoria": "goles",
        "dificultad": "medio",
        "pregunta": "¿Quién marcó este doblete en la final de Qatar 2022 para Argentina?",
        "imagen": "assets/goles/messi_final_2022.png",
        "opciones": ("Julián Álvarez", "Lionel Messi", "Ángel Di María", "Lautaro Martínez"),
        "correcta": 1,
    },
    {
        "id": 35,
        "categoria": "goles",
        "dificultad": "dificil",
        "pregunta": "Este gol de Maradona a Inglaterra en 1986 fue elegido 'Gol del Siglo'. ¿Cuántos rivales eludió?",
        "imagen": "assets/goles/gol_del_siglo.png",
        "opciones": ("3", "4", "5", "6"),
        "correcta": 2,
    },
    {
        "id": 36,
        "categoria": "goles",
        "dificultad": "dificil",
        "pregunta": "¿Quién marcó el polémico 'gol fantasma' en la final del Mundial de 1966?",
        "imagen": "assets/goles/hurst_1966.png",
        "opciones": ("Bobby Charlton", "Geoff Hurst", "Bobby Moore", "Roger Hunt"),
        "correcta": 1,
    },
    {
        "id": 37,
        "categoria": "goles",
        "dificultad": "dificil",
        "pregunta": "Pelé marcó un doblete en una final del Mundial con solo 17 años. ¿En qué Mundial fue?",
        "imagen": "assets/goles/pele_1958.png",
        "opciones": ("Suiza 1954", "Suecia 1958", "Chile 1962", "Inglaterra 1966"),
        "correcta": 1,
    },
    {
        "id": 38,
        "categoria": "goles",
        "dificultad": "facil",
        "pregunta": "¿Quién marcó 3 goles (hat-trick) en la final del Mundial 2022 y aun así perdió?",
        "imagen": "assets/goles/mbappe_final_2022.png",
        "opciones": ("Antoine Griezmann", "Olivier Giroud", "Kylian Mbappé", "Randal Kolo Muani"),
        "correcta": 2,
    },

    # ============ DATOS DEL MUNDIAL (texto) - 12 ============
    {
        "id": 39,
        "categoria": "datos",
        "dificultad": "facil",
        "pregunta": "¿Qué selección ganó el Mundial de Qatar 2022?",
        "imagen": "",
        "opciones": ("Francia", "Brasil", "Argentina", "Croacia"),
        "correcta": 2,
    },
    {
        "id": 40,
        "categoria": "datos",
        "dificultad": "facil",
        "pregunta": "¿En qué países se juega el Mundial 2026?",
        "imagen": "",
        "opciones": (
            "EE.UU., México y Canadá",
            "España, Portugal y Marruecos",
            "Argentina, Uruguay y Paraguay",
            "Solo Estados Unidos",
        ),
        "correcta": 0,
    },
    {
        "id": 41,
        "categoria": "datos",
        "dificultad": "facil",
        "pregunta": "¿Qué selección tiene más Mundiales ganados (5)?",
        "imagen": "",
        "opciones": ("Alemania", "Italia", "Argentina", "Brasil"),
        "correcta": 3,
    },
    {
        "id": 42,
        "categoria": "datos",
        "dificultad": "facil",
        "pregunta": "¿Cada cuántos años se juega la Copa del Mundo?",
        "imagen": "",
        "opciones": ("2 años", "3 años", "4 años", "5 años"),
        "correcta": 2,
    },
    {
        "id": 43,
        "categoria": "datos",
        "dificultad": "medio",
        "pregunta": "¿Qué país organizó y ganó el primer Mundial en 1930?",
        "imagen": "",
        "opciones": ("Brasil", "Uruguay", "Italia", "Argentina"),
        "correcta": 1,
    },
    {
        "id": 44,
        "categoria": "datos",
        "dificultad": "medio",
        "pregunta": "¿Quién es el máximo goleador histórico de los Mundiales (16 goles)?",
        "imagen": "",
        "opciones": ("Ronaldo Nazário", "Miroslav Klose", "Gerd Müller", "Pelé"),
        "correcta": 1,
    },
    {
        "id": 45,
        "categoria": "datos",
        "dificultad": "medio",
        "pregunta": "¿Contra qué selección perdió Brasil 7-1 en la semifinal de su propio Mundial (2014)?",
        "imagen": "",
        "opciones": ("Argentina", "Países Bajos", "Alemania", "Francia"),
        "correcta": 2,
    },
    {
        "id": 46,
        "categoria": "datos",
        "dificultad": "medio",
        "pregunta": "¿En qué Mundial volvió a clasificar Perú después de 36 años?",
        "imagen": "",
        "opciones": ("Brasil 2014", "Rusia 2018", "Qatar 2022", "Sudáfrica 2010"),
        "correcta": 1,
    },
    {
        "id": 47,
        "categoria": "datos",
        "dificultad": "medio",
        "pregunta": "¿Cuántos equipos participan en el Mundial 2026 (nuevo formato)?",
        "imagen": "",
        "opciones": ("32", "40", "48", "64"),
        "correcta": 2,
    },
    {
        "id": 48,
        "categoria": "datos",
        "dificultad": "dificil",
        "pregunta": "¿Qué selección ha jugado TODOS los Mundiales de la historia?",
        "imagen": "",
        "opciones": ("Alemania", "Brasil", "Argentina", "Italia"),
        "correcta": 1,
    },
    {
        "id": 49,
        "categoria": "datos",
        "dificultad": "dificil",
        "pregunta": "¿Quién ganó la Bota de Oro del Mundial México 1970, donde Perú llegó a cuartos?",
        "imagen": "",
        "opciones": ("Pelé", "Gerd Müller", "Teófilo Cubillas", "Jairzinho"),
        "correcta": 1,
    },
    {
        "id": 50,
        "categoria": "datos",
        "dificultad": "dificil",
        "pregunta": "¿Qué arquero es el único capitán arquero en levantar la Copa del Mundo (1982)?",
        "imagen": "",
        "opciones": ("Gianluigi Buffon", "Dino Zoff", "Sepp Maier", "Iker Casillas"),
        "correcta": 1,
    },
]


def cargar_preguntas():
    """Devuelve la lista completa de preguntas (lista de diccionarios)."""
    return LISTA_TRIVIA
